/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import persistencia.Persistencia;



public class B_Administracion extends javax.swing.JFrame {
    
    private Persistencia pst;
 
    
    public B_Administracion(Persistencia pst) {
        
        
        initComponents();
        this.pst = pst;
        this.setExtendedState(MAXIMIZED_BOTH);
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemEgresos = new javax.swing.JMenuItem();
        itemIngresos = new javax.swing.JMenuItem();
        itemCategoria = new javax.swing.JMenuItem();
        itemPersonas = new javax.swing.JMenuItem();
        itemRol = new javax.swing.JMenuItem();
        itemUsuarios = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        panelAdministracion = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        itemPersonas1 = new javax.swing.JMenuItem();
        itemUsuarios1 = new javax.swing.JMenuItem();
        itemRol1 = new javax.swing.JMenuItem();
        itemIngresos1 = new javax.swing.JMenuItem();
        itemEgresos1 = new javax.swing.JMenuItem();
        itemCategoria1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenu1.setText("Administrar");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        itemEgresos.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        itemEgresos.setText("Egresos");
        itemEgresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEgresosActionPerformed(evt);
            }
        });
        jMenu1.add(itemEgresos);

        itemIngresos.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        itemIngresos.setText("Ingresos");
        itemIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIngresosActionPerformed(evt);
            }
        });
        jMenu1.add(itemIngresos);

        itemCategoria.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        itemCategoria.setText("Categoria");
        itemCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCategoriaActionPerformed(evt);
            }
        });
        jMenu1.add(itemCategoria);

        itemPersonas.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        itemPersonas.setText("Personas");
        itemPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPersonasActionPerformed(evt);
            }
        });
        jMenu1.add(itemPersonas);

        itemRol.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        itemRol.setText("Rol");
        itemRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRolActionPerformed(evt);
            }
        });
        jMenu1.add(itemRol);

        itemUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        itemUsuarios.setText("Usuarios");
        itemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUsuariosActionPerformed(evt);
            }
        });
        jMenu1.add(itemUsuarios);

        jMenuBar2.add(jMenu1);

        jMenu2.setText("Opciones");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jMenuItem6.setText("Salir");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar2.add(jMenu2);

        jMenu3.setText("Acerda de ..");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jMenuItem1.setText("Créditos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelAdministracion.setOpaque(false);

        javax.swing.GroupLayout panelAdministracionLayout = new javax.swing.GroupLayout(panelAdministracion);
        panelAdministracion.setLayout(panelAdministracionLayout);
        panelAdministracionLayout.setHorizontalGroup(
            panelAdministracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );
        panelAdministracionLayout.setVerticalGroup(
            panelAdministracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );

        jMenu4.setText("Administrar");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        itemPersonas1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        itemPersonas1.setText("Personas");
        itemPersonas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPersonas1ActionPerformed(evt);
            }
        });
        jMenu4.add(itemPersonas1);

        itemUsuarios1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        itemUsuarios1.setText("Usuarios");
        itemUsuarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUsuarios1ActionPerformed(evt);
            }
        });
        jMenu4.add(itemUsuarios1);

        itemRol1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        itemRol1.setText("Rol");
        itemRol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRol1ActionPerformed(evt);
            }
        });
        jMenu4.add(itemRol1);

        itemIngresos1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        itemIngresos1.setText("Ingresos");
        itemIngresos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIngresos1ActionPerformed(evt);
            }
        });
        jMenu4.add(itemIngresos1);

        itemEgresos1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        itemEgresos1.setText("Egresos");
        itemEgresos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEgresos1ActionPerformed(evt);
            }
        });
        jMenu4.add(itemEgresos1);

        itemCategoria1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        itemCategoria1.setText("Categoria");
        itemCategoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCategoria1ActionPerformed(evt);
            }
        });
        jMenu4.add(itemCategoria1);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Opciones");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jMenuItem7.setText("Salir");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAdministracion)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAdministracion)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemEgresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEgresosActionPerformed
     
    }//GEN-LAST:event_itemEgresosActionPerformed

    private void itemIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIngresosActionPerformed
    
    }//GEN-LAST:event_itemIngresosActionPerformed

    private void itemCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCategoriaActionPerformed
       
    }//GEN-LAST:event_itemCategoriaActionPerformed

    private void itemPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPersonasActionPerformed
        
    }//GEN-LAST:event_itemPersonasActionPerformed

    private void itemRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRolActionPerformed
       
    }//GEN-LAST:event_itemRolActionPerformed

    private void itemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUsuariosActionPerformed
    
    }//GEN-LAST:event_itemUsuariosActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

    }//GEN-LAST:event_jMenuItem1ActionPerformed
    public static G_Egresos e = null;
    private void itemEgresos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEgresos1ActionPerformed
        if (e == null) {
            e = new G_Egresos(pst);
            e.show();
            panelAdministracion.add(e);
        } else {
            e.show();
        }
    }//GEN-LAST:event_itemEgresos1ActionPerformed
    public static F_Ingresos i = null;
    private void itemIngresos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIngresos1ActionPerformed
        if (i == null) {
            i = new F_Ingresos(pst);
            i.show();
            panelAdministracion.add(i);
        } else {
            i.show();
        }
    }//GEN-LAST:event_itemIngresos1ActionPerformed
    public static H_Categoria c = null;
    private void itemCategoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCategoria1ActionPerformed
        if (c == null) {
            c = new H_Categoria(pst);
            c.show();
            panelAdministracion.add(c);
        } else {
            c.show();
        }
    }//GEN-LAST:event_itemCategoria1ActionPerformed
    public static C_Personas p = null;
    private void itemPersonas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPersonas1ActionPerformed
        if (p == null) {
            p = new C_Personas(pst);
            p.show();
            panelAdministracion.add(p);
        } else {
            p.show();
        }
    }//GEN-LAST:event_itemPersonas1ActionPerformed
    public static E_Roles r = null;
    private void itemRol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRol1ActionPerformed
        if (r == null) {
            r = new E_Roles(pst);
            r.show();
            panelAdministracion.add(r);
        } else {
            r.show();
        }
    }//GEN-LAST:event_itemRol1ActionPerformed
    public static D_Usuarios u = null;
    private void itemUsuarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUsuarios1ActionPerformed
        if (u == null) {
            u = new D_Usuarios(pst);
            u.show();
            panelAdministracion.add(u);
        } else {
            u.show();
        }
    }//GEN-LAST:event_itemUsuarios1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem7ActionPerformed
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemCategoria;
    private javax.swing.JMenuItem itemCategoria1;
    private javax.swing.JMenuItem itemEgresos;
    private javax.swing.JMenuItem itemEgresos1;
    private javax.swing.JMenuItem itemIngresos;
    private javax.swing.JMenuItem itemIngresos1;
    private javax.swing.JMenuItem itemPersonas;
    private javax.swing.JMenuItem itemPersonas1;
    private javax.swing.JMenuItem itemRol;
    private javax.swing.JMenuItem itemRol1;
    private javax.swing.JMenuItem itemUsuarios;
    private javax.swing.JMenuItem itemUsuarios1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JDesktopPane panelAdministracion;
    // End of variables declaration//GEN-END:variables

}
