package vista;

import controlador.PersonaJpaController;

import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import modelo.Persona;

import persistencia.Persistencia;
import persistencia.Recursos;
import modeloTablas.TablaPersona;

public class C_Personas extends javax.swing.JInternalFrame {

    private TablaPersona modelPersona = new TablaPersona();
    private PersonaJpaController personJpa;
    private Persistencia pst;
    private Persona persona;
    private ListSelectionModel listaPersonaselect;
    private boolean seleccionar = false;

    public C_Personas(Persistencia pst) {

        initComponents();
        this.pst = pst;
        personJpa = new PersonaJpaController(pst.getFactory());
        modelPersona.setFilaPersona(personJpa.findPersonaEntities());//Sentencia que obtiene los datos de la BD

        tablaPersonas.setModel(modelPersona);
         persona = new Persona();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        buttonIpod1 = new org.edisoncor.gui.button.ButtonIpod();
        jLabel8 = new javax.swing.JLabel();
        cbxGenero = new javax.swing.JComboBox<>();
        spinerEdad = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPersonas = new javax.swing.JTable();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, 180, 20));

        buttonIpod1.setBackground(new java.awt.Color(255, 255, 255));
        buttonIpod1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar.png"))); // NOI18N
        buttonIpod1.setText(".\n");
        buttonIpod1.setActionCommand("\n");
        buttonIpod1.setAutoscrolls(true);
        buttonIpod1.setFont(new java.awt.Font("Arial", 0, 1)); // NOI18N
        buttonIpod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIpod1ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonIpod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 0, 50, 50));

        jLabel8.setFont(new java.awt.Font("Raleway", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("BUSCAR:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 80, 20));

        cbxGenero.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        cbxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        jPanel1.add(cbxGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 90, 20));

        spinerEdad.setModel(new javax.swing.SpinnerNumberModel());
        spinerEdad.setBorder(null);
        jPanel1.add(spinerEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 60, -1));

        jLabel14.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        jLabel14.setText("EDAD:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 100, 20));

        txtCorreo.setBorder(null);
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 180, -1));

        jLabel13.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        jLabel13.setText("CORREO:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 238, 100, 20));

        txtDireccion.setBorder(null);
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 180, -1));

        jLabel11.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        jLabel11.setText("DIRECCIÓN:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 100, -1));

        txtCedula.setBorder(null);
        jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 180, -1));

        jLabel1.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        jLabel1.setText("CÉDULA:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 100, -1));

        txtApellidos.setBorder(null);
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 180, -1));

        jLabel10.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        jLabel10.setText("APELLIDOS:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, -1));

        txtNombres.setBorder(null);
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, -1));

        jLabel9.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        jLabel9.setText("NOMBRES:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, -1));

        jLabel12.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        jLabel12.setText("GÉNERO:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 100, 20));

        tablaPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaPersonas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        listaPersonaselect=tablaPersonas.getSelectionModel();
        listaPersonaselect.addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent e){
                if(!e.getValueIsAdjusting()){
                    tbPersonaLineaSeleccionada(tablaPersonas);
                }
            }

        });
        jScrollPane1.setViewportView(tablaPersonas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 970, 400));

        btnLimpiar.setFont(new java.awt.Font("Raleway", 1, 11)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(102, 102, 102));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconoEditar.png"))); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setBorder(null);
        btnLimpiar.setOpaque(false);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 100, 34));

        btnEliminar.setFont(new java.awt.Font("Raleway", 1, 11)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(102, 102, 102));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconoEliminar.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setBorder(null);
        btnEliminar.setOpaque(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 110, 33));

        btnEditar.setFont(new java.awt.Font("Raleway", 1, 11)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(102, 102, 102));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconoActualizar.png"))); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.setBorder(null);
        btnEditar.setBorderPainted(false);
        btnEditar.setOpaque(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 110, 33));

        btnGuardar.setFont(new java.awt.Font("Raleway", 1, 11)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(102, 102, 102));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconoGuardar.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorder(null);
        btnGuardar.setOpaque(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 100, 50));

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void buttonIpod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIpod1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonIpod1ActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
       limpiarDatos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
         crearPersona();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       editarPersona();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarPersona();
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private org.edisoncor.gui.button.ButtonIpod buttonIpod1;
    private javax.swing.JComboBox<String> cbxGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spinerEdad;
    private javax.swing.JTable tablaPersonas;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables

    public void tbPersonaLineaSeleccionada(JTable tabla) {
        if (tabla.getSelectedRow() != -1) {
            seleccionar = true;
            controlBotones();
            persona = modelPersona.getFilaPersona().get(tabla.getSelectedRow());
            txtNombres.setText(persona.getNombre());
            txtApellidos.setText(persona.getApellido());
            txtCedula.setText(persona.getCedula());
            txtDireccion.setText(persona.getDireccion());
            txtCorreo.setText(persona.getCorreo());
            spinerEdad.setValue(persona.getEdad());
            cbxGenero.setSelectedItem(persona.getGenero());
        }
    }

    public void controlBotones() {
        if (seleccionar) {
            btnGuardar.setEnabled(false);
            btnEditar.setEnabled(true);
//            btnLimpiar.setEnabled(false);
            btnEliminar.setEnabled(true);
        } else {
            btnGuardar.setEnabled(true);
            btnEditar.setEnabled(false);
//            btnLimpiar.setEnabled(true);
            btnEliminar.setEnabled(false);
        }
    }

    public void limpiarDatos() {
        txtApellidos.setText("");
        txtCedula.setText("");
        txtCorreo.setText("");
        txtDireccion.setText("");
        txtNombres.setText("");
        cbxGenero.setSelectedIndex(0);
        txtBuscar.setText("");
        spinerEdad.setValue(12);

        seleccionar = false;

        tablaPersonas.getSelectionModel().clearSelection();//Limpia la seleccion de la tabla o la linea resaltada con la flecha

        persona = null; // Despues de obtener la linea seleccionada borra los campos de los txt
        controlBotones();
    }

    public Persona validarCampos() {
        if (!txtNombres.getText().equals("")) {
            persona.setNombre(txtNombres.getText());
            if (!txtApellidos.getText().equals("")) {
                persona.setApellido(txtApellidos.getText());
                if (!txtCedula.getText().equals("")) {
                    persona.setCedula(txtCedula.getText());
                    persona.setDireccion(txtDireccion.getText());
                    if (!txtCorreo.getText().equals("")) {
                        persona.setCorreo(txtCorreo.getText());
                        persona.setEdad(Integer.parseInt(String.valueOf(spinerEdad.getValue())));
                        persona.setGenero(String.valueOf(cbxGenero.getSelectedItem()));
                    } else {
                        Recursos.showMessajes("Ingrese su Correo");
                    }
                } else {
                    Recursos.warning("Sistema de Control de Gastos", "Ingrese su Cédula");
                }
            } else {
                Recursos.warning("Sistema de Control de Gastos", "Ingrese su Apellido");
            }
        } else {
            Recursos.warning("Sistema de Control de Gastos", "Ingrese su Nombre");
        }
        return persona;
    }

    public void crearPersona() {
        try {
//            persona = new Persona(); //Despues de obtener y limpiar los campos vuelve a designar a una persona como vacio
            personJpa.create(validarCampos());
            modelPersona.agregar(persona);
            limpiarDatos();
            Recursos.success("Sistema de Control de Gatos", "Usted se ha registrado correctamente");
        } catch (Exception e) {

        }
    }

    public void editarPersona() {
        if (validarCampos() != null) {
            persona.setNombre(txtNombres.getText());
            persona.setApellido(txtApellidos.getText());
            persona.setCedula(txtCedula.getText());
            persona.setDireccion(txtDireccion.getText());
            persona.setCorreo(txtCorreo.getText());
            persona.setEdad(Integer.parseInt(String.valueOf(spinerEdad.getValue())));
            try {
                personJpa.edit(persona);
                modelPersona.editar(persona);
                limpiarDatos();
            } catch (Exception e) {
            }
            Recursos.success("Sistema de Control de Gastos", "Ha modificado sus datos correctamente");

        } else {
            Recursos.warning("Sistema de Control de Gastos", "No se ha podido modificar sus datos");
        }

    }

    public void eliminarPersona() {
        try {
            personJpa.destroy(persona.getIdPersona());
            modelPersona.eliminar();
            Recursos.success("Sistema de COntrol de Gastos", "Se ha eliminado del registro de forma correcta");
            limpiarDatos();
        } catch (Exception e) {
        }
    }

}
